# Generated by Django 4.1 on 2022-10-17 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('zipCode', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('unitNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('firmName', models.CharField(max_length=255)),
                ('FK_address_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.address', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshotDate', models.DateField(default=django.utils.timezone.now)),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('closePrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1)),
                ('tradeDate', models.DateField(default=django.utils.timezone.now)),
                ('assetQuantity', models.FloatField(default=1.0)),
                ('FK_agent_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.agent')),
                ('FK_asset_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('maturityDate', models.DateField()),
                ('interestRate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('faceValue', models.DecimalField(decimal_places=2, max_digits=11)),
                ('issuer', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=4)),
                ('FK_asset_bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assetman.asset')),
            ],
        ),
        migrations.CreateModel(
            name='MiscAsset',
            fields=[
                ('description', models.CharField(max_length=255)),
                ('FK_asset_misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assetman.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('totalfee', models.DecimalField(decimal_places=2, max_digits=11)),
                ('FK_asset_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assetman.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=6, unique=True)),
                ('yearHigh', models.DecimalField(decimal_places=2, max_digits=9)),
                ('yearLow', models.DecimalField(decimal_places=2, max_digits=9)),
                ('FK_asset_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assetman.asset')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.trade')),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.trade')),
            ],
        ),
        migrations.CreateModel(
            name='AssetUser',
            fields=[
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=255)),
                ('FK_user_assetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('FK_address_assetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.address')),
            ],
        ),
        migrations.CreateModel(
            name='AgentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeType', models.CharField(max_length=1)),
                ('feeRate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('feeFlat', models.DecimalField(decimal_places=2, max_digits=9)),
                ('feeDescription', models.CharField(max_length=255)),
                ('FK_agent_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.agent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('zipCode__lte', 100000)), name='zipCode_lte_100000'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('street', 'city', 'state', 'zipCode', 'unitNum'), name='uniqueAddress'),
        ),
        migrations.AddConstraint(
            model_name='usertrade',
            constraint=models.UniqueConstraint(fields=('FK_user', 'FK_trade'), name='uniqueUserTrade'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(check=models.Q(('action', 'B'), ('action', 'S'), _connector='OR'), name='actionConstraint'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='FK_stock_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.stock'),
        ),
        migrations.AddField(
            model_name='property',
            name='FK_address_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetman.address', unique=True),
        ),
        migrations.AddConstraint(
            model_name='agentfee',
            constraint=models.CheckConstraint(check=models.Q(('feeType', 'F'), ('feeType', 'R'), _connector='OR'), name='feeConstraint'),
        ),
    ]
