# Generated by Django 4.1 on 2022-10-19 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetUser',
            new_name='FintechUser',
        ),
        migrations.RemoveField(
            model_name='currentholdings',
            name='id',
        ),
        migrations.AlterField(
            model_name='currentholdings',
            name='FK_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assetman.trade'),
        ),
    ]
