# Generated by Django 4.1 on 2022-10-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0002_rename_assetuser_fintechuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pricePerAsset',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=13),
        ),
        migrations.AlterField(
            model_name='address',
            name='unitNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yearHigh',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yearLow',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
