# Generated by Django 4.1 on 2022-10-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0003_trade_priceperasset_alter_address_unitnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='FK_address_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetman.address', unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='firmName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
