# Generated by Django 4.1 on 2022-10-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0004_alter_agent_fk_address_agent_alter_agent_firmname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='FK_agent_trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetman.agent'),
        ),
    ]
