# Generated by Django 4.1 on 2022-10-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0006_alter_agent_firmname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksnapshot',
            name='dayHigh',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='dayLow',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=9),
            preserve_default=False,
        ),
    ]
