# Generated by Django 4.1 on 2022-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0007_stocksnapshot_dayhigh_stocksnapshot_daylow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=255, unique=True)),
                ('interestRate', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
