# Generated by Django 4.1 on 2022-11-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0008_mortgagerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='FK_trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetman.trade'),
        ),
    ]
