# Generated by Django 4.1 on 2022-11-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0009_trade_fk_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='unitNum',
            field=models.IntegerField(),
        ),
    ]
