# Generated by Django 4.1 on 2022-11-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0011_alter_address_unitnum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='zipCode_lte_100000',
        ),
        migrations.RemoveConstraint(
            model_name='address',
            name='uniqueAddress',
        ),
    ]
