# Generated by Django 4.1 on 2022-11-05 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0012_remove_address_zipcode_lte_100000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fintechuser',
            name='FK_address_assetUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetman.address'),
        ),
    ]
