# Generated by Django 4.1 on 2022-11-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0013_alter_fintechuser_fk_address_assetuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentfee',
            name='feeType',
        ),
    ]
