# Generated by Django 4.1 on 2022-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0014_remove_agentfee_feetype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentfee',
            name='feeConstraint',
        ),
    ]
