# Generated by Django 4.1 on 2022-11-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0015_remove_agentfee_feeconstraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentfee',
            name='feeType',
            field=models.CharField(default='R', max_length=1),
            preserve_default=False,
        ),
    ]
