# Generated by Django 4.1 on 2022-11-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0015_expensecategory_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
