# Generated by Django 4.1 on 2022-11-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetman', '0016_agentfee_feetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentfee',
            name='feeType',
        ),
    ]
