# Generated by Django 4.1 on 2022-11-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetman', '0016_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fintechuser',
            name='FK_user_assetUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fintechuser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
