# Generated by Django 4.1 on 2022-08-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
