# Generated by Django 4.1 on 2022-09-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
