# Generated by Django 4.1 on 2022-09-17 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentFile',
        ),
    ]
